create table if not exists telemetry (
  id bigint generated by default as identity primary key,
  device_name text not null,
  category text not null,
  protocol text not null,
  cpu_usage double precision not null,
  memory_usage double precision not null,
  bandwidth_mbps double precision not null,
  latency_ms double precision not null,
  temperature_c double precision not null,
  packet_loss double precision not null,
  created_at timestamptz not null default now()
);

create table if not exists alerts (
  id bigint generated by default as identity primary key,
  device_name text not null,
  severity text not null,
  title text not null,
  message text not null,
  protocol text not null,
  created_at timestamptz not null default now()
);

create or replace function cleanup_old_rows()
returns void
language plpgsql
as $$
begin
  delete from telemetry where id in (
    select id from telemetry order by created_at asc limit greatest((select count(*) from telemetry) - 10, 0)
  );

  delete from alerts where id in (
    select id from alerts order by created_at asc limit greatest((select count(*) from alerts) - 10, 0)
  );
end;
$$;
